edition = "2021"
newline_style = "Native"

max_width = 90

use_small_heuristics = "Off"
fn_call_width = 74
attr_fn_like_width = 74
struct_lit_width = 30
struct_variant_width = 40
array_width = 72
chain_width = 70
single_line_if_else_max_width = 45

use_field_init_shorthand = true
use_try_shorthand = true

match_block_trailing_comma = true

# unstable stuff, which is only used in a nightly toolchain (to use it either be on a
# nightly toolchain or pass +nightly to rustfmt/cargo fmt

format_macro_matchers = true
format_macro_bodies = true

version = "Two"

format_code_in_doc_comments = true
doc_comment_code_block_width = 90
format_strings = true

group_imports = "StdExternalCrate"
imports_granularity = "Crate"
