SHELL=/bin/bash # for path/{a,b} expansion

clean:
	rm -rf .github/ c_lib/ CONTRIBUTING.md docs/ LICENSE-APACHE LICENSE-MIT README.md rustfmt.toml TODO.md xtask/ python_lib/xtask
	rm -rf pauli_tracker/{archive/,src/,xdocs/}
	rm -rf pauli_tracker/tests/roundtrips/mod.rs
