[package]
name = "mbqc_scheduling"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.76"
clap = "4.4.11"
hashbrown = "0.14.3"
itertools = "0.12.0"
# clap = "~4.2.7" # higher requires rustc 1.70
# pauli_tracker = { version = "0.3.2", features = ["serde", "scheduler"] }
pauli_tracker = { version = "0.3.2-alpha.1", git = "https://github.com/taeruh/pauli_tracker.git",  features = ["serde", "circuit"] }
rustc-hash = "1.1.0"
scoped_threadpool = "0.1.9"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.51"

[dev-dependencies]
proptest = "1.2.0"
# rand_pcg = "0.3.1"
