name: pypublish
on:
  push:
    tags:
      - "pv*.*.*"
permissions:
  contents: read
  id-token: write
  pages: write

jobs:

  build:
    uses: ./.github/workflows/pypackage.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/mbqc-scheduling
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist # pypi action defaults to that
          pattern: "mbqc_scheduling-*"
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

